### ISSUE TITLE
tr is undefined ... if (tr.length) { 

### ISSUE THREAD

**Issue by tlobinger** [rsms/html5-video#1]
Hi,

I get errors on firefox 3.6.13 (with firebug 1.6) on line 355 this.buffered is not know
and he repeats that error on and on

In chrome it kind of works

354 .bind('progress', function(ev){
355 var tr = this.buffered;
356 if (tr.length) {
357 // todo: support multiple TimeRange's
358 bufbarq.width(hvideo.barRect.width *
359 ((this.buffered.end(0)-this.buffered.start(0)) / this.duration));
360 }

Thanks in advance

**Comment by rsms** [comment]
The API might have changed or Firefox is lagging after standards (WebKit is normally leading the HTML5 frontier). Let me know if you found a solution and I might be able to patch it in. Thanks.

**Comment by tlobinger** [comment]
sorry I didn't find a quick fix - I will look into videojs.com although it's kind of bloated - thanks anyway
